### ISSUE TITLE
Publish kuska-handshake on crates.io?

### ISSUE THREAD

**Issue by Alexis211** [Kuska-ssb/handshake#72]
Hi,

I'd like to publish on crates.io a crate that depends on kuska-handshake, but it seems that I can't do that for the moment because kuska-handshake itself is not on crates.io. Are you considering publishing it anytime soon?

**Comment by Dhole** [comment]
First of all, thanks for using kuska-handshake!
After seeing this issue, we have discussed publishing the crate on crates.io and we are working towards it! (there is some minor work that we have to do)

**Comment by Dhole** [comment]
@Alexis211 we have just published the crate! https://crates.io/crates/kuska-handshake
I'll close this issue.

**Comment by Alexis211** [comment]
Great news, thanks!
